### ISSUE TITLE
What Subreddits Use a-centralized-mirror?

### ISSUE THREAD

**Issue by AnushK-Fro** [kyleratti/a-centralized-mirror#10]
Just curious what subreddits use a-centralized-mirror bot. I'm looking into expanding into more subreddits instead of just PublicFreakout.

**Comment by kyleratti** [comment]
Currently it's just PublicFreakout, but I'm open to operating on more! I just could never get any subreddits interested in a mirror bot or a mirror bot listing service.

If you have any subreddits in mind that you'd like to operate through AMB with, I'm happy to help make that happen!

FWIW I've reached out to the following in the past and never heard back:

- /r/Roadcam
- /r/Dashcam
- /r/ConvenientCop
