### ISSUE TITLE
API Offline

### ISSUE THREAD

**Issue by AnushK-Fro** [kyleratti/a-centralized-mirror#13]
Hello,

I believe the API is offline.
```
from requests import post
from json import dumps
from base64 import b64encode
import json

response = post(
    'https://api.amirror.link/mirroredvideos/update',
    headers = {'Content-Type': 'application/json', 'X-ACM-API-Token': 'REDACTED', 'X-ACM-Bot-Token': 'REDACTED'},
    data = dumps({
        'redditPostId': 'nkyduk',
        'url': 'https://mirror.fro.wtf/reddit/post/3184928'
    })
)

print(response.content)
```

This code block returns:
https://paste.fro.wtf/aqezunutas.xml
"The initial connection between Cloudflare\'s network and the origin web server timed out. As a result, the web page can not be displayed."

Moreover, it isn't commenting on any posts anymore.

I suspect that it might have been because of some sort of DDoS attack. Yesterday, my mirror/server went offline/extremely slowed down for a couple of hours.

**Comment by kyleratti** [comment]
Sorry for the trouble! I noticed this earlier this morning. I will take care of it this evening.

**Comment by kyleratti** [comment]
This should be resolved. Please let me know if you're still having trouble!

**Comment by AnushK-Fro** [comment]
No rush, I believe I'm getting a 422 error now, is that normal?

**Comment by kyleratti** [comment]
`422` is `Unprocessable Entity`, which should only happen if your JSON payload doesn't match the expected format.

In your snippet there, you have `redditPostId` and `url` properties on the root object. Can you try putting them inside the `data` property?

```json
{
	"data": {
		"redditPostId": "nkyduk",
		"url": "https://mirror.fro.wtf/reddit/post/3184928"
	}
}
```

Wrapping the in a `data` property is a bit non-standard and not really the right way to design a REST endpoint, but unfortunately I made that decision long before I learned that and we're stuck with it until I version the endpoint in the re-write (one day!)

**Comment by kyleratti** [comment]
Looks like the bot is processing your submissions now: https://www.reddit.com/user/a-mirror-bot

**Comment by AnushK-Fro** [comment]
Thank you so much!
