### ISSUE TITLE
Error 422 

### ISSUE THREAD

**Issue by AnushK-Fro** [kyleratti/a-centralized-mirror#5]
Hi,

I've basically got everything with my bot working other than communicating with your API.
I've written it in Python and here is the code I tried:

```
from requests import post
from json import dumps
from base64 import b64encode
import json

response = post(
    'https://api.amirror.link/mirroredvideos/update',
    headers = {'X-ACM-API-Token': 'REDACTED', 'X-ACM-Bot-Token': 'REDACTED'},
    data = dumps({
        'data': {
            'redditPostId': 'kll7xp',
            'url': 'https://mirror.fro.wtf/mirror.php?file=kll7xp.mp4'
        }
    })
)
    
print(response.json())
```
Is there something wrong with this? This outputs: `{'status': {'status': 422, 'message': {}}}`

Same with this code:

```
from requests import post
from json import dumps
from base64 import b64encode
import json

response = post(
    'https://api.amirror.link/mirroredvideos/update',
    headers = {'X-ACM-API-Token': 'REDACTED', 'X-ACM-Bot-Token': 'REDACTED'},
    data = dumps({
        'redditPostId': 'kll7xp',
        'url': 'https://mirror.fro.wtf/mirror.php?file=kll7xp.mp4'
    })
)
    
print(response.json())
```
Is there something that I've done wrong?

Thanks!

**Comment by kyleratti** [comment]
Hi there. This is definitely a bug as I am able to reproduce this on the `GET /mirroredvideos/all` endpoint. However, I am still able to `POST /mirroredvideos/update` using your keys and the data you provided.

Body:

```json
{
	"data": {
		"redditPostId": "kll7xp",
		"url": "https://mirror.fro.wtf/mirror.php?file=kll7xp.mp4"
	}
}
```

It has been a while since I've used Python, but try setting your `Content-Type` header to `application/json`?

**Comment by kyleratti** [comment]
(you can see I was able to successfully POST it here: https://www.reddit.com/r/PublicFreakout/comments/kll7xp/man_picks_fight_with_a_motorcyclist_in_walmart/gh9nqz9/)

**Comment by AnushK-Fro** [comment]
Hello,

Setting the Content-Type header to application/json fixed it, thank you so much!

**Comment by kyleratti** [comment]
Excellent! Let me know if you run into any more issues!

I will work on more descriptive error messages for the future.
