### ISSUE TITLE
Tuckbot 

### ISSUE THREAD

**Issue by AnushK-Fro** [kyleratti/a-centralized-mirror#9]
Hello,
I operate mirror.fro.wtf, and I was wondering if I could have the database files and video files to Tuckbot. I'm willing to host it under mirror.fro.wtf so previous content will still remain available. I wasn't sure where to ask this. I can provide somewhere to upload the files.
Thank you!

**Comment by kyleratti** [comment]
Hey Fro, are you a part of the [PublicFreakout Discord](https://discord.gg/tcneqz7)? Happy to discuss this there if so.
